FROM ruby:2.3-alpine
RUN apk add --no-cache \
    build-base \
    libxml2-dev \
    libxslt-dev \
    postgresql-dev \
    imagemagick \
    tzdata \
    nodejs \
    clang \
    coreutils

RUN bundle config build.nokogiri --use-system-libraries

WORKDIR /evans

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY config/site.yml.example config/site.yml

COPY . .

CMD ["sh", "-c", "bundle exec rake db:create db:migrate spec:languages:cpp"]
